# NUMPY

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])

In [3]:
list1 = [1.0, 2.0, 3.0]

In [4]:
# to convert a list to an array
array2 = np.array(list1)

np.str # string
np.bool # boolean (i.e., True|False)
np.int # integer
np.float # floating point
np.complex # complex (i.e., 1+1j)

In [5]:
# currently, array1 is an integer array
# if we want to convert that integer array into a float array, 
# we need to use an associated function (with an underscore). For example
array3 = np.float_(array1)

In [6]:
print(array1)
print(array3)

[1 2 3]
[1. 2. 3.]


## Multidimensionality

Numpy arrays can be N-dimensional, which is of particular use with tables of data (i.e. 2-D)

In [7]:
array4 = np.array([[1, 2], [3, 4], [5, 6]])
print(array4)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
array4.shape

(3, 2)

In [9]:
array4.size

6

In [10]:
array4[:,1]

array([2, 4, 6])

In [11]:
array4[1,:]

array([3, 4])

In [12]:
array4.flatten()

array([1, 2, 3, 4, 5, 6])

In [13]:
array4.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
array4.reshape((6,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# Special Array Creation Functions

In [15]:
array5 = np.arange(10)
print(array5)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
array6 = np.arange(0,50,5)
print(array6)

[ 0  5 10 15 20 25 30 35 40 45]


In [17]:
array7 = np.ones(10)
print(array7)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [18]:
array8 = np.zeros((3,5))
print(array8)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
array9 = np.identity(6)
print(array9)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


## Some Built-in Numpy Functionality

In [20]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
array6.min(), array6.max()

(0, 45)

In [22]:
array1 = np.arange(1,10,1.0)
array1.mean(), array1.sum(), array1.prod()

(5.0, 45.0, 362880.0)

In [23]:
array10 = np.random.randint(1,10,12).reshape((4,3))
print(array10)

[[8 7 4]
 [3 3 5]
 [4 1 2]
 [9 1 5]]


In [24]:
# average of columns
array10.mean(axis=0)

array([6., 3., 4.])

In [25]:
# average of rows
array10.mean(axis=1)

array([6.33333333, 3.66666667, 2.33333333, 5.        ])

In [26]:
# sum of columns
array10.sum(axis=0)

array([24, 12, 16])

In [27]:
# sum of rows
array10.sum(axis=1)

array([19, 11,  7, 15])

In [28]:
print(array10)

[[8 7 4]
 [3 3 5]
 [4 1 2]
 [9 1 5]]


In [29]:
array10.transpose()

array([[8, 3, 4, 9],
       [7, 3, 1, 1],
       [4, 5, 2, 5]])

In [30]:
array10.T

array([[8, 3, 4, 9],
       [7, 3, 1, 1],
       [4, 5, 2, 5]])

In [31]:
array10.swapaxes(0, 1)

array([[8, 3, 4, 9],
       [7, 3, 1, 1],
       [4, 5, 2, 5]])

In [32]:
# # RESHAPING

In [33]:
np.arange(90).reshape((9, 10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [34]:
np.arange(90).reshape((-1, 10))
#   here -1 means "hey python, you determine the length along this axis"

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [35]:
array1 = np.arange(90).reshape((-1, 10))
array1.shape == (9, 10)

True

In [36]:
# Let's change some elements and observe where they are

In [37]:
array1[0,0]= 1000
print(array1)

[[1000    1    2    3    4    5    6    7    8    9]
 [  10   11   12   13   14   15   16   17   18   19]
 [  20   21   22   23   24   25   26   27   28   29]
 [  30   31   32   33   34   35   36   37   38   39]
 [  40   41   42   43   44   45   46   47   48   49]
 [  50   51   52   53   54   55   56   57   58   59]
 [  60   61   62   63   64   65   66   67   68   69]
 [  70   71   72   73   74   75   76   77   78   79]
 [  80   81   82   83   84   85   86   87   88   89]]


In [38]:
array1[5,:]= np.ones(10)
print(array1)

[[1000    1    2    3    4    5    6    7    8    9]
 [  10   11   12   13   14   15   16   17   18   19]
 [  20   21   22   23   24   25   26   27   28   29]
 [  30   31   32   33   34   35   36   37   38   39]
 [  40   41   42   43   44   45   46   47   48   49]
 [   1    1    1    1    1    1    1    1    1    1]
 [  60   61   62   63   64   65   66   67   68   69]
 [  70   71   72   73   74   75   76   77   78   79]
 [  80   81   82   83   84   85   86   87   88   89]]


In [39]:
array1[:,4]= np.zeros(9)
print(array1)

[[1000    1    2    3    0    5    6    7    8    9]
 [  10   11   12   13    0   15   16   17   18   19]
 [  20   21   22   23    0   25   26   27   28   29]
 [  30   31   32   33    0   35   36   37   38   39]
 [  40   41   42   43    0   45   46   47   48   49]
 [   1    1    1    1    0    1    1    1    1    1]
 [  60   61   62   63    0   65   66   67   68   69]
 [  70   71   72   73    0   75   76   77   78   79]
 [  80   81   82   83    0   85   86   87   88   89]]


In [40]:
array1[3,1:8] = 2*np.ones(7)
print(array1)

[[1000    1    2    3    0    5    6    7    8    9]
 [  10   11   12   13    0   15   16   17   18   19]
 [  20   21   22   23    0   25   26   27   28   29]
 [  30    2    2    2    2    2    2    2   38   39]
 [  40   41   42   43    0   45   46   47   48   49]
 [   1    1    1    1    0    1    1    1    1    1]
 [  60   61   62   63    0   65   66   67   68   69]
 [  70   71   72   73    0   75   76   77   78   79]
 [  80   81   82   83    0   85   86   87   88   89]]


In [41]:
# -1 means "last"
array1[5:-1,1:3] = [[3,3],[3,3],[3,3]]
print(array1)

[[1000    1    2    3    0    5    6    7    8    9]
 [  10   11   12   13    0   15   16   17   18   19]
 [  20   21   22   23    0   25   26   27   28   29]
 [  30    2    2    2    2    2    2    2   38   39]
 [  40   41   42   43    0   45   46   47   48   49]
 [   1    3    3    1    0    1    1    1    1    1]
 [  60    3    3   63    0   65   66   67   68   69]
 [  70    3    3   73    0   75   76   77   78   79]
 [  80   81   82   83    0   85   86   87   88   89]]


In [42]:
# Non-sequential indexing!
array1[(5, 7), (6, 8)] = [-20,-20]
print(array1)

[[1000    1    2    3    0    5    6    7    8    9]
 [  10   11   12   13    0   15   16   17   18   19]
 [  20   21   22   23    0   25   26   27   28   29]
 [  30    2    2    2    2    2    2    2   38   39]
 [  40   41   42   43    0   45   46   47   48   49]
 [   1    3    3    1    0    1  -20    1    1    1]
 [  60    3    3   63    0   65   66   67   68   69]
 [  70    3    3   73    0   75   76   77  -20   79]
 [  80   81   82   83    0   85   86   87   88   89]]


In [44]:
# a = b vs a = copy(b)
array1 = np.array([1, 2, 3]) 
array2 = array1
print('Before______')
print(array2)
array1[0] = 5
print('After_______')
print(array2)

Before______
[1 2 3]
After_______
[5 2 3]


In [45]:
# Numpy arrays are generally passed by reference (to minimize space used in memory)
# This is why when we made a change in array1 above, we also changed array2
#
# To ensure that values are independent, use the copy function:
array1 = np.array([1, 2, 3]) 
array2 = np.copy(array1)
print('Before______')
print(array2)
array1[0] = 5
print('After_______')
print(array2)

Before______
[1 2 3]
After_______
[1 2 3]


In [48]:
### READING IN TEXT (ASCII) FILES WITH LOADTXT
array1 = np.loadtxt('../files/dat_files/mydata.dat')
print(array1)

[[ 6.9117671e+03 -3.5992590e-02  2.8010100e+05]
 [ 6.9168730e+03 -3.9081634e-02  2.7886300e+05]
 [ 6.9217030e+03 -4.2193483e-02  2.7814900e+05]
 [ 6.9268344e+03 -4.5165576e-02  2.7729200e+05]
 [ 6.9317399e+03 -4.7365589e-02  2.6570700e+05]]


In [49]:
# There are lots of options on this function, so check the docs, but some of the most used:
# array2 = np.loadtxt(filename, dtype=dtype, comments=‘#’, delimiter=‘,’, skiprows=5,
#  usecols=(0, 1, 2))
# This skips all comments (designated with a #) and 
# the first 5 rows. It then reads in columns 0, 1, 
# and 2, delimited by a comma

### Mathematical Operations

In [51]:
array1 = np.array([0.5, 1.0, 1.5, 2.0])
print(array1+5)

[5.5 6.  6.5 7. ]


In [52]:
print(array1*2)

[1. 2. 3. 4.]


In [53]:
print(array1**2)

[0.25 1.   2.25 4.  ]


In [54]:
array2 = np.copy(array1)
print(array1 + array2)

[1. 2. 3. 4.]


In [55]:
print(array1*array2)

[0.25 1.   2.25 4.  ]


In [57]:
np.log10(array1)

array([-0.30103   ,  0.        ,  0.17609126,  0.30103   ])

In [58]:
np.exp(array1)

array([1.64872127, 2.71828183, 4.48168907, 7.3890561 ])

In [59]:
np.sin(array1)

array([0.47942554, 0.84147098, 0.99749499, 0.90929743])

In [60]:
np.cosh(array1)

array([1.12762597, 1.54308063, 2.35240962, 3.76219569])

## Matrix Math

In [61]:
# For 2-D (and higher) matrices, you can do standard matrix math:
arr1 = np.array([[0,1],[2,3]])
arr2 = np.array([[4,5],[6,7]])

In [62]:
# Doing standard matrix math: 
np.dot(arr1, arr2)  # dot product

array([[ 6,  7],
       [26, 31]])

In [63]:
# Cross product
np.cross(arr1, arr2) 

array([-4, -4])

In [64]:
# Eigenvalues and eigenvectors
np.linalg.eig(arr1) 

(array([-0.56155281,  3.56155281]), array([[-0.87192821, -0.27032301],
        [ 0.48963374, -0.96276969]]))

In [65]:
# calculating inverses:
np.linalg.inv(arr1)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [67]:
# determinant
np.linalg.det(arr1)

-2.0

### Searching Arrays

In [68]:
arr1 = np.arange(6).reshape((2,3))
print(arr1)

[[0 1 2]
 [3 4 5]]


In [71]:
# following command gives the elements of arr1 > 1
np.where(arr1 > 1)

(array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [74]:
print(arr1[0, 2])

2


In [75]:
print(arr1[1, 0])

3


In [78]:
# you can use more than one criteria
# but in that case we should use extra ()s as follows 
np.where((arr1 > 1) & (arr1<4))

(array([0, 1]), array([2, 0]))

## Vectorizing Functions

In [86]:
# Sometimes, you’ll want to make complex functions that don’t 
# necessarily automatically work with numpy arrays.
# SoLution: vectorization.
# Let's see how vectorization works with an example

In [83]:
def funct1(val):
    import numpy as np
    if val < np.pi/2: # Doesn’t work with array
        x = np.sin(val)
    else:
        x = np.cos(val)
    return x

In [84]:
z = np.linspace(0,np.pi,5)
funct1(z) # will fail

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [85]:
# Now it will work
vfunct1 = np.vectorize(funct1)
vfunct1(z)

array([ 0.00000000e+00,  7.07106781e-01,  6.12323400e-17, -7.07106781e-01,
       -1.00000000e+00])

## Saving your output

In [87]:
# For individual numpy arrays, there are some quick and dirty methods to save your data:

In [88]:
# Quick and Dirty in Text: 
x = np.arange(100).reshape((25,4))
np.savetxt('test.dat', x)

In [90]:
# Numpy also has some proprietary formats (.npy, .npz) that allow for quick reading of data
# Saving a single array: 
np.save('test.npy', arr1)

# Saving multiple arrays: 
x2 = np.arange(20).reshape((5,4))
np.savez('test', a1=x, a2=x2)   # .npz suffix added

### Loading Saved Output

In [92]:
# To load a single numpy array (.npy file): 
arr1 = np.load('test.npy')
print(arr1)

[[0 1 2]
 [3 4 5]]


In [94]:
# To load a multiple numpy arrays (.npz file): 
alldata = np.load('test.npz')
# All Data Object is dictionary-like:
var1 = alldata['a1']
var2 = alldata['a2']
print(var1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]
 [48 49 50 51]
 [52 53 54 55]
 [56 57 58 59]
 [60 61 62 63]
 [64 65 66 67]
 [68 69 70 71]
 [72 73 74 75]
 [76 77 78 79]
 [80 81 82 83]
 [84 85 86 87]
 [88 89 90 91]
 [92 93 94 95]
 [96 97 98 99]]


## LAMBDA FUNCTIONS

In [98]:
# Sometimes you want to define a simple function without the full function syntax. 
# Lambda functions exist for this exact reason: 
# Defining the Function:
funct1 = lambda x: x**2 # Returns the square of x

In [100]:
# Using the Function:
tmpvar1 = funct1(5)
print(tmpvar1)

25


In [101]:
# Can use multiple variables:
funct2 = lambda x,y: x + y

In [102]:
# Using the Function:
tmpvar2 = funct2(5, 6) 
print(tmpvar2)

11


In [103]:
# LAMBDA FUNCTIONS ARE VERY USEFUL IN E.D.A